apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgebalancer-server
  namespace: edgebalancer
  labels:
    app: edgebalancer-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgebalancer-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: edgebalancer-server
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: edgebalancer-server
          image: ghcr.io/ankansaha/edgebalancer-server:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: edgebalancer-env
          env:
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 400Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3